"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/guides.html?#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""
import sys
import functools
from qtpy.QtCore import Qt
from qtpy.QtGui import QIcon, QMovie
from qtpy.QtWidgets import (
    QDialog, QDialogButtonBox, QFileDialog, QHBoxLayout, QLabel,
    QPushButton, QScrollArea, QToolButton, QVBoxLayout, QWidget, QSizePolicy, QApplication
)
class LoadingDialog(QDialog):
    def __init__(self, text="Loading..."):
        super().__init__()
        self.setWindowTitle("Please wait")
        layout = QVBoxLayout()

        self.label_text = QLabel(text)
        layout.addWidget(self.label_text)

        self.spinner_label = QLabel()
        layout.addWidget(self.spinner_label)

        self.setLayout(layout)
        self.setModal(True)

        # Load the spinner GIF
        self.movie = QMovie("icons/spinner.gif")  # Path to your spinner gif file
        self.spinner_label.setMovie(self.movie)
        self.movie.start()

        self.adjustSize()

loading_dialog = LoadingDialog("Loading TopoStats...")
loading_dialog.show()
QApplication.processEvents() 
import inspect
import json
import re
from argparse import Namespace
from pathlib import Path
from typing import Any, Callable, Dict, TYPE_CHECKING, get_args

import numpy as np
import yaml

from magicgui import magicgui
from magicgui.widgets import CheckBox, Container, create_widget, FunctionGui

from napari import current_viewer
from napari.types import ImageData
from napari.viewer import Viewer


from scipy.ndimage import label
from skimage.util import img_as_float


from napari_topostats.utils import (
    afm2stack, average_background, gaussian_filter,
    median_flattened, remove_nonlinear, remove_quadratic,
    remove_scars, remove_tilt,
)

from topostats.grains import Grains
from topostats.filters import Filters
loading_dialog.close()
AVAILABLE_FUNCTIONS = [{"name": "load_config"},
                        {"name": "run_filters"},
                        {"name": "run_grains", "function_key": "grains", "function_to_run": Grains.find_grains, "type_class": Grains, "path_to_data": 'obj.mask_images["above"]["merged_classes"][:, :, 1]'},
                        {"name": "make_3d"}]

from ._button_grid import ButtonGrid

if TYPE_CHECKING:
    import napari
def remove_scars_from_image(
    image: "napari.types.ImageData",
    removal_iterations: int = 2,
    threshold_low: float = 0.250,
    threshold_high: float = 0.666,
    max_scar_width: int = 4,
    min_scar_length: int = 16,
) -> "napari.types.LayerDataTuple":
    """
    Remove scars from an image.

    Scars are long, typically 1-4 pixels wide streaks of high or low data in AFM images. They are a problem
    resulting from random errors in the AFM data collection process and are hard to avoid. This function
    detects and removes these artefacts by interpolating over them between the pixels above and below them.
    This method takes no parameters as it uses parameters already established as instance variables when the
    class was instantiated.

    Parameters
    ----------
    img : npt.NDArray
        A 2-D image to remove scars from.
    filename : str
        The filename (used for logging outputs only).
    removal_iterations : int
        The number of times the scar removal should run on the image.
        Running just once sometimes isn't enough to remove some of the
        more difficult to remove scars.
    threshold_low : float
        A value that when multiplied with the standard deviation, acts as a threshold to determine if an increase
        or decrease in height might constitute the top or bottom of a scar.
    threshold_high : float
        A floating point value that is used similarly to threshold_low, however sharp inclines or descents
        that result in values in the mask higher than this threshold are automatically considered scars.
    max_scar_width : int
        A value that dictates the maximum width that a scar can be. Note that this does not mean horizontal width,
        rather vertical, this is because we consider scars to be laying flat, horizontally, so their width is
        vertical and their length is horizontal.
    min_scar_length : int
        An integer that restricts the algorithm to only mark scars that are as long or longer than this length.
        This is important for ensuring that noise or legitimate but sharp datapoints do not get detected as scars.
        Note that length here is horizontal, as scars are thin, horizontal features.

    Returns
    -------
    self.img
        The original 2-D image with scars removed, unless the config has run set to False, in which case it
        will not remove the scars.
    """
    return (remove_scars(image, removal_iterations, threshold_low, threshold_high, max_scar_width, min_scar_length), {}, "image")


#@magicgui(
#    auto_call=True,
#    row_alignment_quantile={"widget_type": "FloatSlider", "min": 0, "max": 1}
#)
def median_align_rows(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
    row_alignment_quantile: float = 0.5,
) -> "napari.types.LayerDataTuple":
    """
    Flatten images using median differences.

    Flatten the rows of an image, aligning the rows and centering the median around zero. When used with a mask,
    this has the effect of centering the background data on zero.

    Note this function does not handle scars.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D image of the data to align the rows of.
    mask : napari.types.ImageData
        Boolean array of points to mask (ignore).
    row_alignment_quantile : float
        Quantile (in the range 0.0 to 1.0) used for defining the average background, by default 0.5.

    Returns
    -------
    npt.NDArray
        Copy of the input image with rows aligned.
    """
    return (median_flattened(image=image, mask=mask, row_alignment_quantile=row_alignment_quantile), {}, "image")

def remove_planar_tilt(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Remove the planar tilt from an image (linear in 2D spaces).

    Uses a linear fit of the medians of the rows and columns to determine the linear slants in x and y directions
    and then subtracts the fit from the columns.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D image of the data to remove the planar tilt from.
    mask : napari.types.ImageData
        Boolean array of points to mask (ignore).

    Returns
    -------
    napari.types.LayerDataTuple
        Numpy array of image with tilt removed.
    """
    return (remove_tilt(image=image, mask=mask), {}, "image")

def remove_quadratic_background(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Remove the quadratic bowing that can be seen in some large-scale AFM images.

    Use a simple quadratic fit on the medians of the columns of the image and then subtracts the calculated
    quadratic from the columns.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D image of the data to remove the quadratic from.
    mask : napari.types.LabelsData, optional
        Boolean array of points to mask (ignore), by default None.

    Returns
    -------
    napari.types.LayerDataTuple
        Image with the quadratic bowing removed.
    """
    return (remove_quadratic(image=image, mask=mask), {}, "image")

def remove_nonlinear_background(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Fit and remove a "saddle" shaped nonlinear polynomial from the image.

    "Saddles" with the form a + b * x * y - c * x - d * y from the supplied image. AFM images sometimes contain a
    "saddle" shape trend to their background, and so to remove them we fit a nonlinear polynomial of x and y and
    then subtract the fit from the image.

    If these trends are not removed, then the image will not flatten properly and will leave opposite diagonal
    corners raised or lowered.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D numpy height-map array of floats with a polynomial trend to remove.
    mask : napari.types.ImageData, optional
        2-D Numpy boolean array used to mask any points in the image that are deemed not to be part of the
        height-map's background data, by default None

    Returns
    -------
    napari.types.LayerDataTuple
        Image with the polynomial trend subtracted.
    """
    return (remove_nonlinear(image=image, mask=mask), {}, "image")

def zero_average_background(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Zero the background by subtracting the non-masked mean from all pixels.

        Parameters
        ----------
        image : napari.types.ImageData
            Numpy array representing the image.
        mask : napari.types.LabelsData
            Mask of the array, should have the same dimensions as image.

        Returns
        -------
        napari.types.LayerDataTuple
            Numpy array of image zero averaged.
    """
    return (average_background(image=image, mask=mask), {}, "image")

def gaussian_filter_image(
    image: "napari.types.ImageData",
    sigma: float = 2.0,
) -> "napari.types.LayerDataTuple":
    """
    Apply Gaussian filter to an image.

    Parameters
    ----------
    image : "napari.types.ImageData"
        Numpy array representing the image.
    sigma : float
        The standard deviation for the gaussian kernel in the skimage.filters.gaussian() function.

    Returns
    -------
    napari.types.LayerDataTuple
        Numpy array that represent the image after Gaussian filtering.
    """
    return (gaussian_filter(image=image, sigma=sigma), {}, "image")

@magicgui(
    call_button="Run Filters",
    filename={"label": "Filename"},
    pixel_to_nm_scaling={"label": "Pixel to nm scaling"},
)
def run_filters(
    viewer: Viewer,
    napari_img_layer: ImageData,
    filename: str = "image",
    pixel_to_nm_scaling: float = 1.0,
) -> None:
    """Napari widget to run Filters.filter_image() using the loaded config."""
    global config_wrapper, full_config_container

    if config_wrapper is None or full_config_container is None:
        print("Please load a config file first using 'Load Config'.")
        return

    try:
        # Update config with any edits from the GUI
        updated_values = collect_values(full_config_container)
        config_wrapper.flat.update(updated_values)
        full_current_config = config_wrapper.unflatten()

        # Extract filter config
        filter_config = full_current_config.get("filter", {})

        # Enforce required defaults
        filter_config["direction"] = "above"

        filter_config.setdefault("threshold_std_dev", {})
        filter_config["threshold_std_dev"].setdefault("above", 1.0)
        filter_config["threshold_std_dev"].setdefault("below", 10.0)

        filter_config.setdefault("threshold_absolute", {})
        filter_config["threshold_absolute"].setdefault("above", 1.0)
        filter_config["threshold_absolute"].setdefault("below", -1.0)

        filter_config.setdefault("remove_scars", {})
        filter_config["remove_scars"].setdefault("run", False)

        # Filter out valid init args
        sig = inspect.signature(Filters.__init__)
        accepted_params = set(sig.parameters.keys()) - {"self"}
        filtered_config = {k: v for k, v in filter_config.items() if k in accepted_params}

        image_np = np.asarray(napari_img_layer)

        # Run filtering
        filter_obj = Filters(
            image=image_np,
            filename=filename,
            pixel_to_nm_scaling=pixel_to_nm_scaling,
            **filtered_config,
        )
        filter_obj.filter_image()

        filtered = filter_obj.images.get("gaussian_filtered")
        if filtered is not None:
            viewer.add_image(filtered, name=f"{filename} - filtered")
        else:
            print("No filtered image found in output.")

    except Exception as e:
        print(f"Filtering failed: {e}")
        import traceback
        traceback.print_exc()


def resolve_chain(obj, attr_str):
    i = 0
    while i < len(attr_str):
        if attr_str[i] == "[":
            obj = getattr(obj, attr_str[:i])
            attr_str = attr_str[i + 1:attr_str.index("]")]
            i = 0
        i += 1

    parts = attr_str.split(".")
    for part in parts:
        obj = getattr(obj, part)
    return obj


def get_topostats_filter_widget():
    return run_topostats_filter_widget

class ConfigWrapper:
    def __init__(self, config: dict):
        self.original = config
        self.flat = self._flatten(config)

    def _flatten(self, d, parent_key='', sep='.'):
        items = {}
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            if isinstance(v, dict):
                items.update(self._flatten(v, new_key, sep=sep))
            else:
                items[new_key] = v
        return items

    def unflatten(self) -> dict:
        result = {}
        for k, v in self.flat.items():
            keys = k.split('.')
            d = result
            for part in keys[:-1]:
                d = d.setdefault(part, {})
            d[keys[-1]] = v
        return result

def extract_inline_comments(yaml_path: Path, top_level_key: str = None) -> Dict[str, str]:
    """
    Extracts inline comments from a YAML file.
    (This function remains the same as our last debugged version)
    """
    comment_map = {}
    key_stack = [] 

    if not yaml_path.exists():
        print(f"Error: YAML file not found at {yaml_path}")
        return {}

    with open(yaml_path, "r") as f:
        for line_num, line in enumerate(f, 1):
            stripped_line = line.strip()

            if not stripped_line or stripped_line.startswith("#"):
                continue

            match = re.match(r"^(\s*)([a-zA-Z0-9_]+):\s*(?:[^#\n]*?)(?:#\s*(.*))?$", line)
            
            if match:
                indent_str, key_name, comment_text = match.groups()
                indent_level = len(indent_str.replace("\t", "  ")) // 2

                key_stack = key_stack[:indent_level]
                key_stack.append(key_name)

                full_yaml_key_path = ".".join(key_stack)
                final_key_for_map = full_yaml_key_path
                
                if top_level_key:
                    if full_yaml_key_path == top_level_key:
                        final_key_for_map = ""
                    elif full_yaml_key_path.startswith(top_level_key + "."):
                        final_key_for_map = full_yaml_key_path[len(top_level_key) + 1:]

                if comment_text is not None and final_key_for_map:
                    comment_map[final_key_for_map] = comment_text.strip()
    return comment_map

def create_info_icon(tooltip_text: str) -> QToolButton:
    button = QToolButton()
    icon = QIcon.fromTheme("help-about")
    
    if icon and not icon.isNull():
        button.setIcon(icon)
    else:
        button.setText("?")
        font = button.font()
        font.setBold(True)
        button.setFont(font)
        
    button.setToolTip(tooltip_text)
    button.setAutoRaise(True)
    button.setCursor(Qt.WhatsThisCursor)
    return button

def build_dynamic_widget(flat_config: Dict[str, Any], descriptions: Dict[str, str] = None) -> Container:
    widgets = []
    for key, value in flat_config.items():
        current_tooltip_text = descriptions.get(key, "") if descriptions else ""

        if isinstance(value, bool):
            w = create_widget(name=key, widget_type="CheckBox", value=value)
        elif isinstance(value, int):
            w = create_widget(name=key, widget_type="SpinBox", value=value)
        elif isinstance(value, float):
            w = create_widget(name=key, widget_type="FloatSpinBox", value=value)
        elif isinstance(value, str):
            w = create_widget(name=key, widget_type="LineEdit", value=value)
        elif isinstance(value, list):
            w = create_widget(name=key, widget_type="LineEdit", value=str(value))
        elif value is None:
            w = create_widget(name=key, widget_type="LineEdit", value="None")
        else:
            continue

        label = QLabel(w.name)
        label.setTextInteractionFlags(Qt.TextSelectableByMouse)

        if current_tooltip_text:
            w.native.setToolTip(current_tooltip_text)
            label.setToolTip(current_tooltip_text)

        w.label = label
        widgets.append(w)
    return Container(widgets=widgets)


def collect_values(container: Container) -> Dict[str, Any]:
    result = {}
    for widget in container:
        val = widget.value
        name = widget.name
        if isinstance(val, str) and val.strip().startswith("["):
            try:
                import ast
                val = ast.literal_eval(val)
            except (ValueError, SyntaxError):
                pass
        elif val == "None":
            val = None
        result[name] = val
    return result

print("setting config_wrapper and full_config_container to None")
config_wrapper = None
full_config_container = None
comment_descriptions = {}
topostats_widget = None

def open_config_editor(viewer: Viewer):
    global config_wrapper, full_config_container, comment_descriptions

    if config_wrapper is None:
        print("No config loaded.")
        return
    
    # Keys to include
    EDITABLE_TOP_LEVEL_KEYS = {"filter", "grains"}

    # Keys to exclude
    EXCLUDED_KEYS = {"filter.run", "grains.run"}

    filtered_flat_config = {
        k: v for k, v in config_wrapper.flat.items()
        if any(k.startswith(f"{prefix}.") for prefix in EDITABLE_TOP_LEVEL_KEYS)
        and k not in EXCLUDED_KEYS
    }

    filtered_descriptions = {
        k: v for k, v in comment_descriptions.items()
        if any(k.startswith(f"{prefix}.") for prefix in EDITABLE_TOP_LEVEL_KEYS)
        and k not in EXCLUDED_KEYS
    }

    fresh_container = build_dynamic_widget(filtered_flat_config, filtered_descriptions)

    dialog = QDialog()
    dialog.setWindowTitle("Edit Filters and Grains Config")
    dialog.resize(600, 800)

    main_layout = QVBoxLayout(dialog)
    scroll_area = QScrollArea()
    scroll_area.setWidgetResizable(True)

    scroll_content = QWidget()
    scroll_layout = QVBoxLayout(scroll_content)

    for widget in fresh_container:
        row = QWidget()
        row_layout = QHBoxLayout(row)
        row_layout.addWidget(widget.label)
        row_layout.addWidget(widget.native)

        tooltip = widget.native.toolTip()
        if tooltip:
            info_btn = create_info_icon(tooltip)
            row_layout.addWidget(info_btn)

        scroll_layout.addWidget(row)

    scroll_content.setLayout(scroll_layout)
    scroll_area.setWidget(scroll_content)

    button_box = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
    save_button = QPushButton("Save Config to File")
    button_box.addButton(save_button, QDialogButtonBox.ActionRole)

    def save_to_file():
        updated_values = collect_values(fresh_container)
        config_wrapper.flat.update(updated_values)
        full_config = config_wrapper.unflatten()

        file_path, _ = QFileDialog.getSaveFileName(
            parent=dialog,
            caption="Save Config As",
            filter="YAML Files (*.yaml *.yml);;JSON Files (*.json)"
        )
        if file_path:
            try:
                if file_path.endswith(".json"):
                    with open(file_path, "w") as f:
                        json.dump(full_config, f, indent=2)
                else:
                    with open(file_path, "w") as f:
                        yaml.safe_dump(full_config, f, sort_keys=False)
                print(f"Config saved to {file_path}")
            except Exception as e:
                print(f"Failed to save config: {e}")

    save_button.clicked.connect(save_to_file)
    button_box.accepted.connect(dialog.accept)
    button_box.rejected.connect(dialog.reject)

    main_layout.addWidget(scroll_area)
    main_layout.addWidget(button_box)

    if dialog.exec_():
        updated_values = collect_values(fresh_container)
        config_wrapper.flat.update(updated_values)
        print("Config updated.")
        # Optionally refresh the full container for other use
        full_config_container = build_dynamic_widget(config_wrapper.flat.copy(), comment_descriptions)

@magicgui(
    config_path={"label": "Config file", "mode": "r", "filter": "*.yaml;*.json"}, # Added .json filter
    call_button="Load Config",
    auto_call=True,
)
def load_config(viewer: Viewer, config_path: Path):
    global config_wrapper, full_config_container, comment_descriptions, topostats_widget # Updated global name

    try:
        with open(config_path, "r") as f:
            if config_path.suffix.lower() in [".yaml", ".yml"]:
                config = yaml.safe_load(f)
            elif config_path.suffix.lower() == ".json":
                config = json.load(f)
            else:
                print("Unsupported config format.")
                return
    except Exception as e:
        print(f"Failed to load config: {e}")
        return

    comment_descriptions = extract_inline_comments(config_path)
    
    config_wrapper = ConfigWrapper(config) 
    
    full_config_container = build_dynamic_widget(config_wrapper.flat.copy(), comment_descriptions)
    print(config)
    print(config_wrapper)
    if full_config_container is None:
        print("Failed to create full config container.")
        return
    btn = QPushButton("Edit Config")
    btn.clicked.connect(lambda: open_config_editor(viewer))
    viewer.window.add_dock_widget(btn, name="Edit Full Config") # Updated dock widget name
    if topostats_widget is None:
        print("No TopoStatsRootWidget found in viewer.")
    if topostats_widget is not None:
        topostats_widget.function_grid.update_functions(topostats_widget.get_functions())


def get_load_config_widget():
    return load_config

def add_values_to_dict_from_config(
    config: Dict[str, Any],
    wrapper: ConfigWrapper,
    function_key: str,
    args: Dict[str, Any],
    params: list,):
    # for key, value in config.items():
    #     print(f"Processing key: {key}, value: {value}")
    
    #     if value is not None and key in [p.name for p in params]:
    #         args[key] = value
    for param_name in [p.name for p in params]:
        if param_name in config:
            args[param_name] = config[param_name]

        for flat_key, flat_val in wrapper.flat.items():
            if flat_key.startswith(f"{function_key}.") and flat_key[len(f"{function_key}."):] == param_name:
                args[param_name] = flat_val
                break
        # Is this not redundant?
        if param_name in config and isinstance(config[param_name], dict):
            args[param_name] = config[param_name]
    return args

# def show_warning(message: str, time_displayed: float = 3.0):
#     """
#     Show a warning message in the console and optionally display it in the GUI.
#     """
#     print(f"Warning: {message}")
#     if hasattr(current_viewer(), 'window'):
#         current_viewer().window.status = message
#         QApplication.processEvents()
#         QTimer.singleShot(int(time_displayed * 1000), lambda: current_viewer().window.status = "")

def _eval(obj: Any, string: str) -> Any:
    print(f"Entering _eval with object type: {type(obj)} and string: '{string}'")

    string = string.replace(" ", "")
    if string == "":
        print("Empty string, returning object.")
        return obj

    if string[0] == "[":
        print("Detected indexing...")
        next_punc = next_punctuation(string, 1, checking_for=",()[].")
        print(f"Next punctuation: '{string[next_punc]}' at index {next_punc}" if next_punc != -1 else "No valid punctuation found")
        if next_punc != -1 and string[next_punc] == ",":
            axes = []
            print("Multi-axis indexing detected")
            for i in string[1:string.index("]", 1)].split(","):
                if i == ":":
                    axes.append(slice(None))
                    print("Adding full slice ':'")
                elif i.isdigit():
                    axes.append(int(i))
                    print(f"Adding int index: {i}")
            subscript = tuple(axes)
            print(f"Using subscript tuple: {subscript}")
            obj = obj[subscript]
        else:
            subscript = string[1:string.index("]", 1)]
            print(f"Single subscript: {subscript}")
            if subscript.isdigit():
                obj = obj[int(subscript)]
                print(f"Indexing with integer: {int(subscript)}")
            else:
                key = subscript.replace("'", "").replace('"', '')
                obj = obj[key]
                print(f"Indexing with key: {key}")
        remaining = string[string.index("]", 1) + 1:]
        print(f"Continuing evaluation with remaining string: '{remaining}'")
        return _eval(obj, remaining)

    elif string[0] == ".":
        print("Detected attribute or method access")
        index = next_punctuation(string, 1)
        if index == -1:
            attr = string[1:]
            print(f"Attempting final attribute access: {attr}")
            if hasattr(obj, attr):
                print(f"Attribute '{attr}' found.")
                return getattr(obj, attr)
            else:
                raise AttributeError(f"'{type(obj).__name__}' object has no attribute '{attr}'")

        if string[index] == "(":
            func_name = string[1:index]
            print(f"Function call detected: {func_name}")
            if hasattr(obj, func_name):
                func = getattr(obj, func_name)
                args_str = string[index + 1:string.index(")", index + 1)]
                args = [arg.strip() for arg in args_str.split(",") if arg.strip()]
                print(f"Calling function '{func_name}' with args: {args}")
                result = func(*args)
                remaining = string[string.index(")", index + 1) + 1:]
                print(f"Function call result: {result}, continuing with '{remaining}'")
                return _eval(result, remaining)
            else:
                raise AttributeError(f"'{type(obj).__name__}' object has no callable '{func_name}'")
        else:
            attr = string[1:index]
            print(f"Accessing attribute: {attr}")
            if hasattr(obj, attr):
                obj = getattr(obj, attr)
                print(f"Attribute '{attr}' value: {obj}")
            else:
                raise AttributeError(f"'{type(obj).__name__}' object has no attribute '{attr}'")
            remaining = string[index:]
            print(f"Continuing evaluation with remaining string: '{remaining}'")
            return _eval(obj, remaining)

    else:
        print(f"Unknown string start character: '{string[0]}', returning object unchanged.")
        return obj




def next_punctuation(s: str, start: int = 0, checking_for: str = ".([") -> int:
    """Find the next punctuation character in a string."""
    for i in range(start, len(s)):
        if s[i] in checking_for:
            return i
    return -1
        
class CallableWithSignature:
    def __init__(self, real_func, sig):
        functools.update_wrapper(self, real_func)  # Sets __name__, __doc__, etc.
        self.real_func = real_func
        self.__signature__ = sig

    def __call__(self, *args, **kwargs):
        bound = self.__signature__.bind(*args, **kwargs)
        bound.apply_defaults()
        return self.real_func(**bound.arguments)
    

def is_binary_image(arr: np.ndarray) -> bool:
    unique_vals = np.unique(arr) 
    # Check if unique values are subset of {0,1}
    return set(unique_vals).issubset({0, 1, 255})

def get_widget(function_key: str, function_to_run: Callable, type_class: type = None, path_to_data: str = None) -> FunctionGui:
    global config_wrapper, full_config_container

    print(f"--- get_widget called with ---")
    print(f"function_key: {function_key}")
    print(f"function_to_run: {function_to_run.__name__}")
    print(f"type_class: {type_class}")
    print(f"path_to_data: {path_to_data}")

    if config_wrapper is None:
        print("⚠️ Config wrapper is None.")
        print("Please load a config file first using 'Load Config'.")
        
    if full_config_container is None:
        print("⚠️ Full config container is None.")
        print("Please load a config file first using 'Load Config'.")
    if config_wrapper is None or full_config_container is None:
        return

    try:
        if path_to_data is None:
            if type_class is not None:
                path_to_data = "obj"
            else:
                path_to_data = "return"
        print(f"Resolved path_to_data: {path_to_data}")

        updated_values = collect_values(full_config_container)
        print("Collected values from full_config_container.")
        config_wrapper.flat.update(updated_values)

        full_current_config = config_wrapper.unflatten()
        config = full_current_config.get(function_key, {})
        print(f"Retrieved config for key '{function_key}': {config}")

        parameters_from_function = [
            p for p in inspect.signature(function_to_run).parameters.values() if p.name != "self"
        ]
        print(f"Function parameters: {[p.name for p in parameters_from_function]}")

        if type_class is not None:
            sig = inspect.signature(type_class.__init__)
            parameters_from_class = [
                p for name, p in sig.parameters.items()
                if name != "self"
            ]
            print(f"Class constructor parameters: {[p.name for p in parameters_from_class]}")
            all_parameters = parameters_from_class + parameters_from_function
        else:
            sig = inspect.signature(function_to_run)
            all_parameters = parameters_from_function

        including_config_params_from_function = parameters_from_function.copy()
        including_config_params_from_class = parameters_from_class.copy() if type_class is not None else []
        filtered_config = {}
        for param_name in [p.name for p in all_parameters]:
            print(f"Looking for parameter '{param_name}' in config...")
            if param_name in config:
                filtered_config[param_name] = config[param_name]
                print(f"Found in config: {param_name} = {config[param_name]}")
                parameters_from_function = [p for p in parameters_from_function if p.name != param_name]
                if type_class is not None:
                    parameters_from_class = [p for p in parameters_from_class if p.name != param_name]
            else:
                for flat_key, flat_val in config_wrapper.flat.items():
                    if flat_key.startswith(f"{function_key}.") and flat_key[len(f"{function_key}."):] == param_name:
                        filtered_config[param_name] = flat_val
                        print(f"Found in flat config: {flat_key} = {flat_val}")
                        parameters_from_function = [p for p in parameters_from_function if p.name != param_name]
                        if type_class is not None:
                            parameters_from_class = [p for p in parameters_from_class if p.name != param_name]
                        break
            if param_name in config and isinstance(config[param_name], dict):
                filtered_config[param_name] = config[param_name]
                print(f"Found dict for param {param_name}: {config[param_name]}")
                parameters_from_function = [p for p in parameters_from_function if p.name != param_name]
                if type_class is not None:
                    parameters_from_class = [p for p in parameters_from_class if p.name != param_name]
        print(f"Parameters after filtering: {[p.name for p in parameters_from_function]}")
        print(f"Class constructor parameters after filtering: {[p.name for p in parameters_from_class]}")
        if type_class is not None:
            def func(**kwargs):
                print("--- Running widget function for class method ---")
                class_args = {}
                method_args = {}
                print(f"Initial kwargs: {kwargs}")
                print(f"Parameters from function: {[p.name for p in including_config_params_from_function]}")
                print(f"Parameters from class: {[p.name for p in including_config_params_from_class]}")

                for key, value in kwargs.items():
                    if key in [p.name for p in including_config_params_from_function]:
                        method_args[key] = value
                    elif key in [p.name for p in including_config_params_from_class]:
                        class_args[key] = value
                print(f"Initial method_args from kwargs: {method_args}")
                print(f"Initial class_args from kwargs: {class_args}")
                print(f"Config: {config}")
                method_args = add_values_to_dict_from_config(
                    config, config_wrapper, function_key, method_args, including_config_params_from_function
                )
                class_args = add_values_to_dict_from_config(
                    config, config_wrapper, function_key, class_args, including_config_params_from_class
                )

                print(f"Final method_args: {method_args}")
                print(f"Final class_args: {class_args}")

                for key, value in method_args.items():
                    if isinstance(value, get_args(ImageData)):
                        print(f"Converting ImageData to ndarray for key: {key}")
                        method_args[key] = np.asarray(value.data)
                for key, value in class_args.items():
                    if isinstance(value, get_args(ImageData)):
                        print(f"Converting ImageData to ndarray for key: {key}")
                        class_args[key] = np.asarray(value.data)

                print("Creating instance of class...")
                instance = type_class(**class_args)
                method = getattr(instance, function_to_run.__name__, None)
                if method:
                    print(f"Calling method {function_to_run.__name__}")
                    return_value = method(**method_args)
                    print(f"Return value: {return_value}")

                    if path_to_data.startswith("return"):
                        return_value = _eval(return_value, path_to_data[6:]) if len(path_to_data) > 6 else return_value
                    elif path_to_data.startswith("obj"):
                        return_value = _eval(instance, path_to_data[3:]) if len(path_to_data) > 3 else instance
                    else:
                        raise ValueError(f"Invalid path_to_data: {path_to_data}")
                    
                    if return_value is not None:
                        viewer = kwargs["viewer"] if "viewer" in kwargs else current_viewer()
                        print(f"Adding return_value to viewer. Type: {type(return_value)}")
                        if isinstance(return_value, np.ndarray):
                            if is_binary_image(return_value):
                                labels, num_labels = label(return_value.astype(bool))
                                label_ids = list(range(1, num_labels + 1))
                                properties = {"label_id": label_ids}
                                viewer.add_labels(
                                    labels.astype(np.uint16),
                                    name=f"{function_key.title()} Mask",
                                    properties=properties
                                )
                            else:
                                viewer.add_image(
                                    return_value,
                                    name=f"{function_key.title()} Image",
                                    contrast_limits=(-1, 5),
                                )
                    else:
                        print(f"Function {function_to_run.__name__} returned None.") 
            new_parameters = []
            for p in parameters_from_function + parameters_from_class:
                if p.name == "image":
                    new_p = p.replace(default=None)
                    new_p = new_p.replace(annotation=ImageData)
                elif p.name == "pixel_to_nm_scaling":
                    new_p = p.replace(default=1.0)
                elif p.name == "filename":
                    new_p = p.replace(default="image")
                else:
                    new_p = p
                new_parameters.append(new_p)
            print(f"New parameters for magicgui: {[p.name for p in new_parameters]}")
            wrapped_func = CallableWithSignature(func, inspect.Signature(parameters=new_parameters))
            
        else:
            def func(**kwargs):
                print("--- Running widget function for standalone function ---")
                method_args = {}

                for key, value in kwargs.items():
                    if key in [p.name for p in including_config_params_from_function]:
                        method_args[key] = value
                print(f"Initial method_args from kwargs: {method_args}")

                method_args = add_values_to_dict_from_config(
                    config, config_wrapper, function_key, method_args, including_config_params_from_function
                )

                for key, value in method_args.items():
                    if isinstance(value, ImageData):
                        print(f"Converting ImageData to ndarray for key: {key}")
                        method_args[key] = np.asarray(value.data)

                print(f"Calling standalone function: {function_to_run.__name__} with args: {method_args}")
                function_to_run(method_args)

            wrapped_func = CallableWithSignature(func, inspect.Signature(parameters=new_parameters))

        print("Wrapping function with magicgui")
        return magicgui()(wrapped_func)

    except Exception as e:
        print(f"❌ Exception in get_widget: {e}")
        raise

    
@magicgui(
    call_button="Run Grains",
    filename={"label": "Filename"},
    pixel_to_nm_scaling={"label": "Pixel to nm scaling"},
)
def run_grains(
    viewer: Viewer,
    napari_img_layer: ImageData,
    filename: str = "image",
    pixel_to_nm_scaling: float = 1.0,
) -> None:
    global config_wrapper, full_config_container

    if config_wrapper is None or full_config_container is None:
        print("Please load a config file first using 'Load Config'.")
        return

    try:
        updated_values = collect_values(full_config_container)
        config_wrapper.flat.update(updated_values)

        full_current_config = config_wrapper.unflatten()
        grains_config = full_current_config.get("grains", {})

        sig = inspect.signature(Grains.__init__)
        accepted_params = set(sig.parameters.keys()) - {"self", "image", "filename", "pixel_to_nm_scaling"}
        print(f"Accepted parameters for Grains: {accepted_params}")
        filtered_grains_config = {}
        for param_name in accepted_params:
            if param_name in grains_config:
                filtered_grains_config[param_name] = grains_config[param_name]

            for flat_key, flat_val in config_wrapper.flat.items():
                if flat_key.startswith("grains.") and flat_key[len("grains."):] == param_name:
                    filtered_grains_config[param_name] = flat_val
                    break

            if param_name in grains_config and isinstance(grains_config[param_name], dict):
                filtered_grains_config[param_name] = grains_config[param_name]

        image_np = np.asarray(napari_img_layer.data)
        print(f"Calling Grains with config: {filtered_grains_config}")
        
        grains_obj = Grains(
            image=image_np,
            filename=filename,
            pixel_to_nm_scaling=pixel_to_nm_scaling,
            **filtered_grains_config
        )
        grains_obj.find_grains()

        try:
            merged = grains_obj.mask_images["above"]["merged_classes"][:, :, 1]

            # Label each grain individually
            labeled_grains, num_grains = label(merged.astype(bool))

            # Simple properties with grain_id
            grain_ids = list(range(1, num_grains + 1))
            properties = {"grain_id": grain_ids}

            # Add labeled mask to napari with grain properties
            viewer.add_labels(
                labeled_grains.astype(np.uint16),
                name="Grain Mask",
                properties=properties
            )

        except Exception as e:
            print(f"Failed to add merged_classes mask: {e}")

    except Exception as e:
        print(f"Grain detection failed: {e}")
        import traceback
        traceback.print_exc()


def get_grains_widget():
    return run_grains

@magicgui(
    call_button="3D-ify Image",
)
def make_3d(
    viewer: Viewer,
    image: ImageData,
    filename: str = "image",
    bySlices: bool = True,
    min_slices: int = 255,
    resolution: float = 1.0,
) -> ImageData:
    """
    Convert an AFM height image into a pseudo volume by via the pixel values.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D numpy height-map array.
    bySlices : bool, optional
        Convert to voxels by creating N slices or cut at a Z resolution, by default True.
    min_slices : int, optional
        Number of voxel slices, by default 255
    resolution : float, optional
        Size of voxel height, by default 1.0

    Returns
    -------
    napari.types.ImageData
        3-D slices of the AFM height image.
    """
    stack = afm2stack(
        image=image,
        by_slices=bySlices,
        numslices=min_slices,
        resolution=resolution,
    )
    viewer.add_image(stack,
                    name=f"{filename} - 3D-ified",
                    contrast_limits=(-1, 5),)
    viewer.dims.ndisplay = 3

# if we want even more control over our widget, we can use
# magicgui `Container`
class ImageThreshold(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        # use create_widget to generate widgets from type annotations
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )
        self._threshold_slider = create_widget(
            label="Threshold", annotation=float, widget_type="FloatSlider"
        )
        self._threshold_slider.min = 0
        self._threshold_slider.max = 1
        # use magicgui widgets directly
        self._invert_checkbox = CheckBox(text="Keep pixels below threshold")
        Image(self._viewer, self._image_layer_combo.value)

        # connect your own callbacks
        self._threshold_slider.changed.connect(self._threshold_im)
        self._invert_checkbox.changed.connect(self._threshold_im)

        # append into/extend the container with your widgets
        self.extend(
            [
                self._image_layer_combo,
                self._threshold_slider,
                self._invert_checkbox,
            ]
        )

    def _threshold_im(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            return

        image = img_as_float(image_layer.data)
        name = image_layer.name + "_thresholded"
        threshold = self._threshold_slider.value
        if self._invert_checkbox.value:
            thresholded = image < threshold
        else:
            thresholded = image > threshold
        if name in self._viewer.layers:
            self._viewer.layers[name].data = thresholded
        else:
            self._viewer.add_labels(thresholded, name=name)

class TopoStatsRootWidget(QWidget):
    def __init__(self, viewer: Viewer):
        super().__init__()
        global topostats_widget
        self._viewer = viewer
        layout = QVBoxLayout(self)
        self.function_grid = ButtonGrid(
            self,
            functions=self.get_functions(),
            viewer=self._viewer
        )
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.function_grid.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        layout.setContentsMargins(5, 5, 5, 5)
        layout.addWidget(self.function_grid)
        self.setLayout(layout)
        topostats_widget = self
        
    
    def get_functions(self):
        functions = {}
        print(AVAILABLE_FUNCTIONS)
        for function_dict in AVAILABLE_FUNCTIONS:
            function_name = function_dict["name"]
            title = function_name.replace("_", " ").title()
            if "function_key" in function_dict:
                global config_wrapper, full_config_container
                if config_wrapper is None or full_config_container is None:
                    continue
                function_dict.pop("name", None)
                function_key = function_dict["function_key"]
                function_to_run = function_dict["function_to_run"]
                type_class = function_dict["type_class"]
                path_to_data = function_dict["path_to_data"]
                print(f"--- get_widget called with ---")
                print(f"function_key: {function_key}")
                print(f"function_to_run: {function_to_run.__name__}")
                print(f"type_class: {type_class}")
                print(f"path_to_data: {path_to_data}")
                func = get_widget(function_key, function_to_run, type_class, path_to_data)
                print(f"Function {title} found: {func}")
                functions[title] = func
            else:
                func = getattr(sys.modules[__name__], function_name, None)
                print(f"Function {function_name} found: {func}")
                if isinstance(func, FunctionGui):
                    functions[title] = func
                elif callable(func):
                    functions[title] = magicgui(func)
        return functions
    



