"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/guides.html?#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""
import sys
import functools
from qtpy.QtCore import Qt
from qtpy.QtGui import QIcon
from qtpy.QtWidgets import (
    QToolButton, QVBoxLayout, QWidget, QSizePolicy, QApplication
)
from ._alerts import show_error_dialog, LoadingDialog

loading_dialog = LoadingDialog("Loading TopoStats...")
loading_dialog.show()
QApplication.processEvents()
import inspect
import json
from pathlib import Path
from typing import Any, Dict, TYPE_CHECKING

import numpy as np
import yaml

from magicgui import magicgui
from magicgui.widgets import CheckBox, Container, create_widget, FunctionGui

from napari import current_viewer
from napari.types import ImageData
from napari.layers import Image
from napari.viewer import Viewer


from scipy.ndimage import label
from skimage.util import img_as_float


from napari_topostats.utils import (
    afm2stack, average_background, gaussian_filter,
    median_flattened, remove_nonlinear, remove_quadratic,
    remove_scars, remove_tilt,
)

from topostats.grains import Grains
from topostats.filters import Filters

loading_dialog.close()

from ._button_grid import ButtonGrid
from ._widget_function import WidgetFunction
from . import _state as state
from . import _widget_function as gui_utils
from ._io import load_config


if TYPE_CHECKING:
    import napari


AVAILABLE_FUNCTIONS = [WidgetFunction(name="load_config",
                                      tooltip="Load a configuration file to use with TopoStats functions.",
                                      function_to_run=load_config),
                        WidgetFunction(name="run_filters",
                            function_key="filter",
                            function_to_run=Filters.filter_image,
                                type_class=Filters,
                                path_to_data='obj.images["gaussian_filtered"]',
                                    uses_config=True,
                                    tooltip="Run filters on the selected image using the current configuration."),
                        WidgetFunction(name="run_grains",
                          function_key="grains",
                            function_to_run=Grains.find_grains,
                              type_class=Grains,
                                path_to_data='obj.mask_images["above"]["merged_classes"][:, :, 1]',
                                  uses_config=True,
                                  tooltip="Run grain analysis on the selected image using the current configuration."),
                        WidgetFunction(name="make_3d",
                                       function_key="3d",
                                       function_to_run=afm2stack,
                                       path_to_data="return",
                                       ndims=3,
                                       tooltip="Convert the selected image to a 3D stack"),]


def remove_scars_from_image(
    image: "napari.types.ImageData",
    removal_iterations: int = 2,
    threshold_low: float = 0.250,
    threshold_high: float = 0.666,
    max_scar_width: int = 4,
    min_scar_length: int = 16,
) -> "napari.types.LayerDataTuple":
    """
    Remove scars from an image.

    Scars are long, typically 1-4 pixels wide streaks of high or low data in AFM images. They are a problem
    resulting from random errors in the AFM data collection process and are hard to avoid. This function
    detects and removes these artefacts by interpolating over them between the pixels above and below them.
    This method takes no parameters as it uses parameters already established as instance variables when the
    class was instantiated.

    Parameters
    ----------
    img : npt.NDArray
        A 2-D image to remove scars from.
    filename : str
        The filename (used for logging outputs only).
    removal_iterations : int
        The number of times the scar removal should run on the image.
        Running just once sometimes isn't enough to remove some of the
        more difficult to remove scars.
    threshold_low : float
        A value that when multiplied with the standard deviation, acts as a threshold to determine if an increase
        or decrease in height might constitute the top or bottom of a scar.
    threshold_high : float
        A floating point value that is used similarly to threshold_low, however sharp inclines or descents
        that result in values in the mask higher than this threshold are automatically considered scars.
    max_scar_width : int
        A value that dictates the maximum width that a scar can be. Note that this does not mean horizontal width,
        rather vertical, this is because we consider scars to be laying flat, horizontally, so their width is
        vertical and their length is horizontal.
    min_scar_length : int
        An integer that restricts the algorithm to only mark scars that are as long or longer than this length.
        This is important for ensuring that noise or legitimate but sharp datapoints do not get detected as scars.
        Note that length here is horizontal, as scars are thin, horizontal features.

    Returns
    -------
    self.img
        The original 2-D image with scars removed, unless the config has run set to False, in which case it
        will not remove the scars.
    """
    return (remove_scars(image, removal_iterations, threshold_low, threshold_high, max_scar_width, min_scar_length), {}, "image")


#@magicgui(
#    auto_call=True,
#    row_alignment_quantile={"widget_type": "FloatSlider", "min": 0, "max": 1}
#)
def median_align_rows(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
    row_alignment_quantile: float = 0.5,
) -> "napari.types.LayerDataTuple":
    """
    Flatten images using median differences.

    Flatten the rows of an image, aligning the rows and centering the median around zero. When used with a mask,
    this has the effect of centering the background data on zero.

    Note this function does not handle scars.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D image of the data to align the rows of.
    mask : napari.types.ImageData
        Boolean array of points to mask (ignore).
    row_alignment_quantile : float
        Quantile (in the range 0.0 to 1.0) used for defining the average background, by default 0.5.

    Returns
    -------
    npt.NDArray
        Copy of the input image with rows aligned.
    """
    return (median_flattened(image=image, mask=mask, row_alignment_quantile=row_alignment_quantile), {}, "image")

def remove_planar_tilt(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Remove the planar tilt from an image (linear in 2D spaces).

    Uses a linear fit of the medians of the rows and columns to determine the linear slants in x and y directions
    and then subtracts the fit from the columns.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D image of the data to remove the planar tilt from.
    mask : napari.types.ImageData
        Boolean array of points to mask (ignore).

    Returns
    -------
    napari.types.LayerDataTuple
        Numpy array of image with tilt removed.
    """
    return (remove_tilt(image=image, mask=mask), {}, "image")

def remove_quadratic_background(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Remove the quadratic bowing that can be seen in some large-scale AFM images.

    Use a simple quadratic fit on the medians of the columns of the image and then subtracts the calculated
    quadratic from the columns.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D image of the data to remove the quadratic from.
    mask : napari.types.LabelsData, optional
        Boolean array of points to mask (ignore), by default None.

    Returns
    -------
    napari.types.LayerDataTuple
        Image with the quadratic bowing removed.
    """
    return (remove_quadratic(image=image, mask=mask), {}, "image")

def remove_nonlinear_background(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Fit and remove a "saddle" shaped nonlinear polynomial from the image.

    "Saddles" with the form a + b * x * y - c * x - d * y from the supplied image. AFM images sometimes contain a
    "saddle" shape trend to their background, and so to remove them we fit a nonlinear polynomial of x and y and
    then subtract the fit from the image.

    If these trends are not removed, then the image will not flatten properly and will leave opposite diagonal
    corners raised or lowered.

    Parameters
    ----------
    image : napari.types.ImageData
        2-D numpy height-map array of floats with a polynomial trend to remove.
    mask : napari.types.ImageData, optional
        2-D Numpy boolean array used to mask any points in the image that are deemed not to be part of the
        height-map's background data, by default None

    Returns
    -------
    napari.types.LayerDataTuple
        Image with the polynomial trend subtracted.
    """
    return (remove_nonlinear(image=image, mask=mask), {}, "image")

def zero_average_background(
    image: "napari.types.ImageData",
    mask: "napari.types.LabelsData"=None,
) -> "napari.types.LayerDataTuple":
    """
    Zero the background by subtracting the non-masked mean from all pixels.

        Parameters
        ----------
        image : napari.types.ImageData
            Numpy array representing the image.
        mask : napari.types.LabelsData
            Mask of the array, should have the same dimensions as image.

        Returns
        -------
        napari.types.LayerDataTuple
            Numpy array of image zero averaged.
    """
    return (average_background(image=image, mask=mask), {}, "image")

def gaussian_filter_image(
    image: "napari.types.ImageData",
    sigma: float = 2.0,
) -> "napari.types.LayerDataTuple":
    """
    Apply Gaussian filter to an image.

    Parameters
    ----------
    image : "napari.types.ImageData"
        Numpy array representing the image.
    sigma : float
        The standard deviation for the gaussian kernel in the skimage.filters.gaussian() function.

    Returns
    -------
    napari.types.LayerDataTuple
        Numpy array that represent the image after Gaussian filtering.
    """
    return (gaussian_filter(image=image, sigma=sigma), {}, "image")




    
# if we want even more control over our widget, we can use
# magicgui `Container`
class ImageThreshold(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        # use create_widget to generate widgets from type annotations
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )
        self._threshold_slider = create_widget(
            label="Threshold", annotation=float, widget_type="FloatSlider"
        )
        self._threshold_slider.min = 0
        self._threshold_slider.max = 1
        # use magicgui widgets directly
        self._invert_checkbox = CheckBox(text="Keep pixels below threshold")
        Image(self._viewer, self._image_layer_combo.value)

        # connect your own callbacks
        self._threshold_slider.changed.connect(self._threshold_im)
        self._invert_checkbox.changed.connect(self._threshold_im)

        # append into/extend the container with your widgets
        self.extend(
            [
                self._image_layer_combo,
                self._threshold_slider,
                self._invert_checkbox,
            ]
        )

    def _threshold_im(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            return

        image = img_as_float(image_layer.data)
        name = image_layer.name + "_thresholded"
        threshold = self._threshold_slider.value
        if self._invert_checkbox.value:
            thresholded = image < threshold
        else:
            thresholded = image > threshold
        if name in self._viewer.layers:
            self._viewer.layers[name].data = thresholded
        else:
            self._viewer.add_labels(thresholded, name=name)

#Added comments
class TopoStatsRootWidget(QWidget):
    """
    A root widget where all topostats functions can be accessed.
    This widget serves as a container for the button grid and provides
    a layout for the various controls.
    """
    def __init__(self, viewer: Viewer):
        super().__init__()
        # Initialize the widget with a viewer
        self._viewer = viewer
        # Make layout so children are arranged vertically
        layout = QVBoxLayout(self)
        # Add the function grid to the layout with the available functions
        self.function_grid = ButtonGrid(
            self,
            functions=self.get_functions(),
            viewer=self._viewer
        )
        # Set the size policy to allow the widget to expand
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.function_grid.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        # Set the layout margins and add the function grid
        layout.setContentsMargins(5, 5, 5, 5)
        layout.addWidget(self.function_grid)
        # Set the layout for the widget
        self.setLayout(layout)
        
    
    def get_functions(self):
        """
        Get the available functions for the button grid.

        Returns
        -------
        functions : dict[str, WidgetFunction | FunctionGui]
            A dictionary of function names and their corresponding WidgetFunction or FunctionGui objects.
        """
        functions = {}
        for function in AVAILABLE_FUNCTIONS:
            function_name = function.name
            display_name = function_name.replace("_", " ").title()
            if function.path_to_data is not None:
                # This option is used for functions that will be dynamically converted to a widget
                functions[display_name] = function
            else:
                # This option is used for functions that are hardcoded
                func = function.function_to_run
                if isinstance(func, FunctionGui):
                    functions[display_name] = func
                elif callable(func):
                    functions[display_name] = magicgui(func)
        return functions