name: Generate Main CodeCov Report

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Main CodeCov Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - name: Upgrade pip and install test dependencies
        run: |
          pip install --upgrade virtualenv
          pip install --upgrade pip setuptools
          pip show pip setuptools
          virtualenv --upgrade-embed-wheels
          # virtualenv --reset-app-data
          pip install -e .[tests]
      - name: Test with pytest
        run: |
          pytest --cov=napari-afmreader -x
      - name: Determine coverage
        run: |
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
